apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: image-volume
          emptyDir: {}
      containers:
        - name: todo-app
          image: tomirantanen/todo-app:1.12
          volumeMounts:
          - name: image-volume
            mountPath: /app/static/images
