apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-log-output
          emptyDir: {}
      containers:
        - name: log-writer
          image: tomirantanen/log-writer:1.10
          volumeMounts:
          - name: shared-log-output
            mountPath: /app/files
        - name: log-reader
          image: tomirantanen/log-reader:1.10
          volumeMounts:
          - name: shared-log-output
            mountPath: /app/files
