apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: todo-project
  name: todo-cron-job
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: todo-cron-job
              image: tomirantanen/cron-job:2.09
          restartPolicy: Never
