apiVersion: v1
kind: Service
metadata:
  namespace: todo-project
  name: todo-api-service
spec:
  type: ClusterIP
  selector:
    app: todo-api
  ports:
    - port: 2346
      protocol: TCP
      targetPort: 3000
